//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use crate::adapters::database::pool::DbPool;

pub mod permissions;
pub mod role_permissions;
pub mod role_user;
pub mod roles;
pub mod services;
pub mod sessions;
pub mod users;
pub mod default_role;
pub mod init_state;

pub trait CreateIFNotExists {
    async fn create_if_not_exists(&self, db_pool: DbPool) -> Result<(), sqlx::Error>;
}
