//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_state")]
pub enum UserState {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "banned")]
    Banned,
    #[sea_orm(string_value = "deleted")]
    Deleted,
    #[sea_orm(string_value = "inactive")]
    Inactive,
}
