[package]
name = "tobox"
version = "0.1.0"
authors = ["JKearnsl <pooolg@hotmail.com>"]
edition = "2021"
include = ["/src"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = {  version = "^4.8", features = ["rustls-0_23"] }
rustls = "^0.23"
rustls-pemfile = "^2.1"
log = "^0.4"
env_logger = "^0.11"
serde = { version = "^1.0", features = ["derive"] }
serde_yaml = "^0.9.34-deprecated"

